Professional_Services_Consulting: 1
Educational_Technology: 1

Software_as_a_Service_SaaS: 2
Advertising_Marketing_Technology: 2

Ecommerce_Online_Retail: 3
Manufacturing_Discrete: 3

Healthcare_Provider_Digital_Health: 4
Government_IT_Contractor: 4

FinTech_Payments: 5
Energy_Utility_Critical_Infrastructure: 5
